# DESARROLLO Algoritmo Genético en Futbol
 Profundización Automatización y Control.
Desarrollado por:
* Juan José Torres Quiñonez. 220160099.            
* Jonathan David Rosero Moreno. 220160119.

Se aborda el problema de la siguiente forma:
Se requiere un algoritmo que nos arroje los mejores tipos de individuos para un juego de futbol.
Los atributos que consideramos importantes para un jugador son:
Velocidad, Equilibrio, Fuerza, Resistencia.

In [32]:
#Version 3:
import random
import numpy as np

pesosAtributos = [5, 15, 30, 50] #Velocidad: 5, Equilibrio: 15, Fuerza: 30, Resistencia: 50.
generacion = 0

def crear_vectores_aleatorios(n, m):
    # Crear n vectores de tamaño m con valores aleatorios 0 ó 1
    vectores_aleatorios = np.random.randint(2, size=(n, m))
    
    return vectores_aleatorios

# Especifica el número de vectores (n) y el tamaño de cada vector (m)
n = 5 # Variantes de jugadores.
m = 4 # Número de atributos.

# Llama a la función para crear los vectores aleatorios
vectores_generados = crear_vectores_aleatorios(n, m)

# Imprime los vectores generados
generacion=generacion+1
print("Generación: ",generacion)
print("Variantes de jugadores: ")
print(vectores_generados)

#EVALUACIÓN:
print("EVALUACION: ")
resultados_evaluacion = vectores_generados * np.array(pesosAtributos)
print("Resultados de la evaluación:")
#print(resultados_evaluacion)
# Suma los valores de cada fila
suma_por_fila = np.sum(resultados_evaluacion, axis=1)
print("Respectivos resultados de variantes jugadores: ")
print(suma_por_fila)

#RECOMBINACIÓN
print("RECOMBINACION: ")
for i in range(0, n-1):
    A=vectores_generados[0,i]
    B=vectores_generados[1,i]
    eleccion_aleatoria = random.choice([A, B])
    vectores_generados[0,i]=eleccion_aleatoria
for i in range(0, n-1):
    A=vectores_generados[1,i]
    B=vectores_generados[2,i]
    eleccion_aleatoria = random.choice([A, B])
    vectores_generados[2,i]=eleccion_aleatoria
for i in range(0, n-1):
    A=vectores_generados[2,i]
    B=vectores_generados[3,i]
    eleccion_aleatoria = random.choice([A, B])
    vectores_generados[3,i]=eleccion_aleatoria
for i in range(0, n-1):
    A=vectores_generados[3,i]
    B=vectores_generados[4,i]
    eleccion_aleatoria = random.choice([A, B])
    vectores_generados[4,i]=eleccion_aleatoria
generacion=generacion+1
print("Generación: ",generacion)
print("Variantes de jugadores: ")
print(vectores_generados)

#EVALUACIÓN:
print("EVALUACION: ")
resultados_evaluacion = vectores_generados * np.array(pesosAtributos)
print("Resultados de la evaluación:")
#print(resultados_evaluacion)
# Suma los valores de cada fila
suma_por_fila = np.sum(resultados_evaluacion, axis=1)
print("Respectivos resultados de variantes jugadores: ")
print(suma_por_fila)


Generación:  1
Variantes de jugadores: 
[[0 0 0 0]
 [1 0 1 1]
 [0 1 0 1]
 [1 1 1 0]
 [0 0 0 0]]
EVALUACION: 
Resultados de la evaluación:
Respectivos resultados de variantes jugadores: 
[ 0 85 65 50  0]
RECOMBINACION: 
Generación:  2
Variantes de jugadores: 
[[0 0 1 0]
 [1 0 1 1]
 [0 1 1 1]
 [1 1 1 0]
 [1 1 0 0]]
EVALUACION: 
Resultados de la evaluación:
Respectivos resultados de variantes jugadores: 
[30 85 95 50 20]


Otra forma de solucionar el ejercicio es:

In [1]:
import random

# Definición de posiciones de juego
POSICIONES = ['Portero', 'Defensa', 'Centrocampista', 'Delantero']

# Número de jugadores en cada posición
NUM_JUGADORES = {'Portero': 1, 'Defensa': 4, 'Centrocampista': 4, 'Delantero': 2}

# Número total de jugadores en un equipo de fútbol
NUM_JUGADORES_TOTAL = sum(NUM_JUGADORES.values())

# Número de individuos en la población
NUM_INDIVIDUOS = 10

# Número de habilidades por jugador
NUM_HABILIDADES_POR_JUGADOR = 2

# Paso 1: Iniciar Población
def iniciar_poblacion(num_individuos, num_jugadores_total):
    poblacion = []
    for _ in range(num_individuos):
        individuo = {}
        for posicion in POSICIONES:
            individuo[posicion] = [(random.randint(1, 100), random.randint(1, 100)) for _ in range(NUM_JUGADORES[posicion])]
        poblacion.append(individuo)
    return poblacion

# Paso 2: Evaluar Individuos
def evaluar_individuos(poblacion):
    evaluaciones = []
    for individuo in poblacion:
        evaluacion = funcion_evaluacion(individuo)  # Reemplaza funcion_evaluacion con tu propia función
        evaluaciones.append((individuo, evaluacion))
    return evaluaciones

# Paso 3: Recombinación
def recombinar(padre1, padre2):
    hijo = {}
    for posicion in POSICIONES:
        punto_corte = random.randint(0, len(padre1[posicion]) - 1)
        hijo[posicion] = padre1[posicion][:punto_corte] + padre2[posicion][punto_corte:]
    return hijo

# Paso 4: Mutación
def mutar(individuo, tasa_mutacion):
    for posicion in POSICIONES:
        for i in range(len(individuo[posicion])):
            if random.random() < tasa_mutacion:
                habilidad_nueva = (random.randint(1, 100), random.randint(1, 100))
                individuo[posicion][i] = habilidad_nueva  # Cambiar las habilidades del jugador
    return individuo

# Función de evaluación (reemplázala con tu propia función)
def funcion_evaluacion(individuo):
    evaluacion_total = 0
    for posicion in POSICIONES:
        for habilidades in individuo[posicion]:
            evaluacion_total += sum(habilidades)
    return evaluacion_total

# Algoritmo Genético
def algoritmo_genetico(num_generaciones, num_individuos, num_jugadores_total, tasa_mutacion):
    poblacion = iniciar_poblacion(num_individuos, num_jugadores_total)

    for generacion in range(num_generaciones):
        evaluaciones = evaluar_individuos(poblacion)
        evaluaciones.sort(key=lambda x: x[1], reverse=True)  # Ordenar por evaluación descendente

        print(f"Generación {generacion + 1} - Mejor Evaluación: {evaluaciones[0][1]}")

        nueva_poblacion = [evaluaciones[i][0] for i in range(num_individuos // 2)]  # Elitismo: seleccionar los mejores individuos

        # Recombinación y mutación
        for i in range(num_individuos // 2):
            padre1, padre2 = random.choice(evaluaciones)[0], random.choice(evaluaciones)[0]
            hijo = recombinar(padre1, padre2)
            hijo = mutar(hijo, tasa_mutacion)
            nueva_poblacion.append(hijo)

        poblacion = nueva_poblacion

    # Devolver el mejor individuo al final
    mejor_equipo = max(evaluar_individuos(poblacion), key=lambda x: x[1])
    return mejor_equipo

# Parámetros
num_generaciones = 10
num_individuos = 10
tasa_mutacion = 0.1

# Ejecutar el algoritmo genético
mejor_equipo = algoritmo_genetico(num_generaciones, num_individuos, NUM_JUGADORES_TOTAL, tasa_mutacion)

# Mostrar el mejor equipo
print("\nMejor equipo encontrado:")
for posicion, habilidades in mejor_equipo[0].items():
    print(f"{posicion}: {habilidades}")
print(f"Evaluación Total: {mejor_equipo[1]}")

Generación 1 - Mejor Evaluación: 1263
Generación 2 - Mejor Evaluación: 1263
Generación 3 - Mejor Evaluación: 1263
Generación 4 - Mejor Evaluación: 1263
Generación 5 - Mejor Evaluación: 1263
Generación 6 - Mejor Evaluación: 1263
Generación 7 - Mejor Evaluación: 1384
Generación 8 - Mejor Evaluación: 1488
Generación 9 - Mejor Evaluación: 1488
Generación 10 - Mejor Evaluación: 1488

Mejor equipo encontrado:
Portero: [(97, 96)]
Defensa: [(78, 41), (10, 84), (69, 81), (73, 100)]
Centrocampista: [(99, 75), (63, 86), (45, 13), (79, 13)]
Delantero: [(43, 95), (54, 94)]
Evaluación Total: 1488
